### ISSUE TITLE
push fails after using layer deduplication for obdconv

### ISSUE THREAD

**Issue by bengbeng-pp** [containerd/accelerated-container-image#100]
Steps：

1.    ./ctr obdconv --dbstr "username:password@tcp(db_host:port)/db_name" A  B  -> success
3.    ./ctr obdconv --dbstr "username:password@tcp(db_host:port)/db_name" A  C   -> success
4.    ./ctr image push B   -> success
5.    ./ctr image push C   -> failure
        report an error    ->       ctr: "" failed validation: invalid argument

manifest ：
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/53809897/157434162-3d4e0c15-a787-44d3-9c91-0a04e6592ca1.png">

**Comment by liulanzheng** [comment]
@bengbeng-pp  sorry ~ please try #101

**Comment by bengbeng-pp** [comment]
good job , now there is no problem
