### ISSUE TITLE
crictl pull image error

### ISSUE THREAD

**Issue by wxx213** [containerd/accelerated-container-image#102]
With the latest codes, the image download error by 'crictl pull' command.

The error like:
`pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "$dadi_image": failed to prepare extraction snapshot "extract-545136048-IAjX sha256:c3b59cdbc3b160347a81159bc96aca9ceed3995c3d3814304e252e7853c4354f": failed to rename: rename /opt/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/new-061002457 /opt/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/3479: file exists: unknown`

When I clear the containerd root (which include overlaybd-snapshotter root dir), this issue disappear. May be there are some compatibility problems with the old version overlaybd-snapshotter .

**Comment by liulanzheng** [comment]
I also had similar problems in other scenarios. most times it recovered after retrying, sometimes not. The main reason is the data is out of sync between contaienrd and snapshotter after some exceptions, or something else. We will pay more attention to this problem in the future. Since the root cause may be complex so it will take some time.

**Comment by wxx213** [comment]
> I also had similar problems in other scenarios. most times it recovered after retrying, sometimes not. The main reason is the data is out of sync between contaienrd and snapshotter after some exceptions, or something else. We will pay more attention to this problem in the future. Since the root cause may be complex so it will take some time.

More infoformation, this issue also disappear when I clear the snapshots in default namespace by `ctr snapshots rm(someone else may type `ctr rpull` that left these snapshots), you may confirm this if it helps.
