### ISSUE TITLE
create container fails after using layer deduplication for obdconv 

### ISSUE THREAD

**Issue by bengbeng-pp** [containerd/accelerated-container-image#104]
1. Convert image A to image B：
./ctr obdconv --dbstr "username:password@tcp(db_host:port)/db_name" A B 

2. Using image B to create a container fails, and overlaybd reports the following error: 
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/53809897/159431144-3dce49b7-21be-42a9-ac20-24b2dfc44e7b.png">

**Comment by liulanzheng** [comment]
I need more infomation. In fact these errors may have no relationship with deduplication. Could you provide the whole log of overlaybd for lauching this image? that may help.

**Comment by bengbeng-pp** [comment]
Thanks for the answer, I seem to know why. It is a compatibility issue of overlaybd, which is caused by inconsistent overlaybd versions of the build image and the running image.
