### ISSUE TITLE
fail to use 'record-trace' 

### ISSUE THREAD

**Issue by Sugar929** [containerd/accelerated-container-image#110]
When I tried to record trace of an image (obd format), it failed:

`sudo bin/ctr  record-trace registry.hub.docker.com/overlaybd/redis:6.2.6_obd  redis_trace`

`ctr: failed to setup network for namespace: plugin type="loopback" failed (add): failed to find plugin "loopback" in path [/opt/cni/bin/]`

I followed the docs strictly to build the environment, I download `containerd-1.6.0-rc.1-linux-amd64.tar.gz` from containerd.io
All relative information I could get from google was about k8s, What should I do to handle with the problem?

**Comment by beef9999** [comment]
Maybe you didn’t install CNI or its version is too old. Try to disable it with the disable-network-isolation option.

**Comment by beef9999** [comment]
BTW would you like to share your case about where you are going to use trace?

**Comment by Sugar929** [comment]
> 

thank u, I redownloaded containered with CNI, and it worked. But I ran into anothor problem: how can I stop the process of recording? if I press "ctrl+c", the whole programme "bin/ctr record-trace" will stop, so the collectTrace、load trace file、create the new image with trace will not happen. Therefore, I can't get the recorded image. I tried to kill the running task, but the task can't be killed.

**Comment by Sugar929** [comment]
I try to use the trace in a docker slim situation.

**Comment by beef9999** [comment]
The ctr record-trace only forward your signal, i.e. SIGTERM. If your containerd/image doesn't respond to this signal, then it won't be killed.
Maybe you can try the --time option. After 2x times of this, a SIGKILL will be sent.

**Comment by Sugar929** [comment]
I set the --time 10 option, it printed "Timeout, stop recording ...", but I waited for far more than 20sec, the programme still not exited. I checked the path "/tmp/ctr-record-trace" and found the .lock did't be eliminated, so no new image with trace was created

**Comment by Sugar929** [comment]
I added the --time option, but I waited for more than 2x times, the record-trace just print "Timeout, stop recording ..." and didn't be killed, so no new image with trace was created. Then I used rm -f to stop the task, and I got the new image. Although I used "ctr i ls"  and could find it, I couldn't find its files under "var/lib/overlaybd/snapshots", so where can I find it?

**Comment by beef9999** [comment]
I need to update some code to fix this. Please wait for a moment

**Comment by beef9999** [comment]
@Sugar929 Could you try this commit? https://github.com/beef9999/accelerated-container-image/tree/fix-trace

**Comment by Sugar929** [comment]
thank u, the new commit can stop right. But when I use "sudo bin/ctr i ls", there doesn't exist the  image with trace that I want.

**Comment by beef9999** [comment]
1. Are you able to push your image to the hub.docker.com and make it public, it would be easier for us to debug.
2. Are you using trace in production environment or just a research?

**Comment by beef9999** [comment]
@Sugar929 Did you install the overlaybd-service? What its log be like?

**Comment by beef9999** [comment]
@Sugar929 
And it seems you are recording our example image, which already contains the acceleration-layer.

You need to pull an normal tar image, create the corresponding obd image, then record its trace.

**Comment by Sugar929** [comment]
@beef9999 
Yes, I changed a normal tar image, and I got the image with trace. The old version will throw an error if you use an image with acceleration layer, which is not included in the fixed version, so I forgot I shouldn't use wordpress_obd.
Thank you for your detailed and patient answers
