### ISSUE TITLE
Integration with firecracker-containerd

### ISSUE THREAD

**Issue by xxinran** [containerd/accelerated-container-image#116]
I am trying to integrate overlaybd image with firecracker-containerd, which takes firecracker as the runtime instead of runc in containerd.  It is usually used in the case where an isolated environment is required and security is important. 
However, the firecracker does not support virtio-fs, so we can not simply pass the container's rootfs by overlayfs, etc. Fortunately　firecracker supports virtio-blk that allow us to pass a block device to the microVM, so we can pass the container rootfs by the block device.

That's why I want to use overlaydb-snapshotter in `rwDev` mode. 
I labeled the snapshotter with `writable=dev` and then `rpull` the image, it occurs 
```
ctr: failed to commit snapshot extract-199052258-yDl8 sha256:fd84eb22532fcbe372941242bb3ebc762860b26392aaad92fd3b4342a887a66c: failed to commit writable overl
aybd: failed to open file '/var/lib/overlaybd/snapshots/524/block/writable_data', 2: No such file or directory
```
When I unlabeled the snapshotter, and rpull again, it works well.  It seems we should only label the snapshotter as "rwDev" mode during creating container, not pulling the image. 

Could you please explain why we can not label it before `rpull`? 

Another question is, does the prefetching work well in "rwDev" mode?  And how can we verify this?

**Comment by xxinran** [comment]
@liulanzheng  Thanks for your explanation, I also verified prefetching in my environment and it works. 
As for 'rwDev' mode snapshotter fails to pull image with accel-layer, I have a fix here https://github.com/containerd/accelerated-container-image/pull/117, comments are welcomed.

**Comment by liulanzheng** [comment]
@xxinran  thanks
