### ISSUE TITLE
obdconv runs into "writeable file stat failed" 

### ISSUE THREAD

**Issue by juliusl** [containerd/accelerated-container-image#125]
I'm running into this, when trying out the examples, 

![image](https://user-images.githubusercontent.com/5741075/176053715-c4027527-9e49-4635-a4f3-f740087bb28a.png)

Logs don't seem to have much information, just a bunch of start-up output but no errors.

My env is, 

Go lang 1.17.2
Ubuntu 20.04 (Hyper-V VM on Windows 11) 
Runc 1.0
Containerd 1.6.6

Everything seems to be compiling, installing, starting up, etc, but I haven't been able to get obdconv working. If there is any other information I can provide please let me know. Thanks,

**Comment by liulanzheng** [comment]
Thank you. There are changes recently, but lack of E2E testing. give me some time ~

**Comment by juliusl** [comment]
Thanks! I can confirm that fixed my issue.
