### ISSUE TITLE
`ctr run` runs into `Authentication failed`

### ISSUE THREAD

**Issue by juliusl** [containerd/accelerated-container-image#127]
I successfully managed to pull, convert, push, and then rpull my image, but when I try to run the image I run into this error (registry hostname obfuscated): 

![image](https://user-images.githubusercontent.com/5741075/176326282-987b9c05-db3a-4e5f-9319-b514e4de9519.png)

Am I missing an authentication step?

**Comment by BigVan** [comment]
Did you edit the credential file?
the default location is '/opt/overlaybd/cred.json' like this:
```json
{
  "auths": {
    "hub.docker.com": {
      "username": "username",
      "password": "password"
    },
    "hub.docker.com/hello/world": {
      "auth": "dXNlcm5hbWU6cGFzc3dvcmQK"
    }
  }
}
```
please check https://github.com/containerd/overlaybd to find more details.

**Comment by juliusl** [comment]
Just closing the loop, this was indeed the issue, thanks!
