### ISSUE TITLE
Error while running busybox obd image: "failed to attach and mount for snapshot 80: failed to enable target for"

### ISSUE THREAD

**Issue by ganeshkumar5699** [containerd/accelerated-container-image#128]
Hi! We have been able to run overlaybd containers (the redis server and Wordpress ones in the examples) on an AKS nodes, but I face an error when attempting to run a busybox obd image. It would be great if you could help identify the issue. Thanks!

Steps to repro:
`.accelerated-container-image/script/performance/clean-env.sh`

`sudo nerdctl run --net host --rm --pull=always docker.io/library/busybox` # Works

`bin/ctr obdconv docker.io/library/busybox:latest docker.io/aganeshkumar/daditest:busybox_test_obd` # Works

Output:
```
docker.io/aganeshkumar/daditest:busybox_test_obd:                                 resolved       |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:dfcd0a2ff1e99bcb845919322698e1e7a0a11d517e812f8af75b2cc61e90fc11: exists         |++++++++++++++++++++++++++++++++++++++| 
config-sha256:e85ab4f2f7c417565e4cf68c848b59e3d78e29c2fb96196d208180c2f3fb049f:   exists         |++++++++++++++++++++++++++++++++++++++| 
elapsed: 0.6 s                                                                    total:   0.0 B (0.0 B/s)  
```

`nerdctl image push docker.io/aganeshkumar/daditest:busybox_obd` # No error, can see image in this public dockerhub repo

`.accelerated-container-image/script/performance/clean-env.sh` # To remove previously pulled images

`sudo nerdctl run -it --net host --rm --snapshotter=overlaybd docker.io/aganeshkumar/daditest:busybox_test_obd ` # Errors

Error message:
```
FATA[0000] failed to attach and mount for snapshot 80: failed to enable target for /sys/kernel/config/target/core/user_999999999/dev_80, failed:failed to open switch file `https://docker.io/v2/aganeshkumar/daditest/blobs/sha256:58e554736a9008721c7a0918428315cce2678f6440bb39dc9689ef22a809b7ac: unknown 
```

For additional context: 
- This is the script to setup a node on AKS with overlaybd snapshotter: https://github.com/ganeshkumar5699/container-acceleration. I would assume, the same issue is hit even with a regular Linux VM. 
- If we don't remove the converted obd image locally, push the image and then attempt to run it, it works (presumably because the layers already exist locally)

Potential cause of the issue: 
Not all the layers of the obd image are being converted locally or being pushed properly. 

It would be great to know how to make this work, as we want to run benchmarking tests with different converted obd images (starting with `busybox`). Thank you!

**Comment by BigVan** [comment]
Can you tell us the kernel version by `uname -r`
We have seen a similar problem in Azure ubuntu 1804. I don't remember the specific kernel.  @shuaichang

Maybe you can upgrade your kernel version and try again...

**Comment by ganeshkumar5699** [comment]
Thanks for the quick response! It is running on ubuntu 1804 on Azure, and we are on kernel: `5.4.0-1085-azure`

**Comment by ganeshkumar5699** [comment]
I think this is one of the latest images: https://packages.ubuntu.com/bionic/linux-azure. Can it work on Ubuntu 1804 in general?

**Comment by BigVan** [comment]
I found that overlaybd used 'docker.io' as the container registry domain and got an HTML file which led to startup failure. 😂
You can use 'registry-1.docker.io' instead of 'docker.io'...

**Comment by BigVan** [comment]
#132 
@ganeshkumar5699
