### ISSUE TITLE
ctr image push error after convert image where duplicated layers exist

### ISSUE THREAD

**Issue by wxx213** [containerd/accelerated-container-image#141]
The reproduce step:
```
./ctr obdconv --dbstr  $db -u $u:$p $src_image $dest_image

./ctr image rm $dest_image
./ctr obdconv --dbstr  $db -u $u:$p $src_image $dest_image

./ctr image push -u $u:$p $dest_image
```

Then is error is like:
```
manifest-sha256:046152104c87d2debcdc941adceb57a26ceb04ad1a4f12dcc25f4ceeabb3695a: waiting        |--------------------------------------|
elapsed: 0.1 s                                                                    total:   0.0 B (0.0 B/s)
ctr: content digest sha256:5eb52d402f717a0f1148e15131faf9f8e696a2d9756c85939623e9bca5354581: not found
```

It seems that when the remote layer is found in database, ctr obdconv didn't save the layer into local content store.

**Comment by liulanzheng** [comment]
@wxx213  if database is used to deduplication, the new image is designed to upload automatically. the remote layers are still remote and will not download during conversion.

**Comment by wxx213** [comment]
> @wxx213 if database is used to deduplication, the new image is designed to upload automatically. the remote layers are still remote and will not download during conversion.

Got it, thanks.
