### ISSUE TITLE
ctr from release v0.5.2 failed to run on ubuntu 20.04

### ISSUE THREAD

**Issue by northtyphoon** [containerd/accelerated-container-image#155]
Repro:

- Install [v0.5.2](https://github.com/containerd/accelerated-container-image/releases/tag/v0.5.2) on `ubuntu 20.04`
- run `/opt/overlaybd/snapshotter/ctr`  

Error:

/opt/overlaybd/snapshotter/ctr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/overlaybd/snapshotter/ctr)

**Comment by northtyphoon** [comment]
Not sure about the root cause, I'm wondering if the released binaries could be built by disabling cgo?

**Comment by liulanzheng** [comment]
thank you very much~ i guess it is because the update of golang version, and it is solved by disabling cgo.

**Comment by liulanzheng** [comment]
v0.5.2 is updated

**Comment by northtyphoon** [comment]
Thanks for the quick fix. It works.

**Comment by paralin** [comment]
@liulanzheng Please don't update tags (force push). This is because downstream this repo is used as a Go module which has a checksum in go.sum, and a version in the Go module proxy servers. Now there is a mismatch between the version served from the Go module proxy servers and the one served from GitHub which causes a build error if `GOPROXY=direct`.

**Comment by AkihiroSuda** [comment]
> v0.5.2 is updated

@liulanzheng 
Could you share what was the previous commit hash of v0.5.2 (current: fd022b910830015d8665a7b497f47bba1f90dd18)
I assume it was 71d70d4e738679154f62e2869e94784558cb9b36 ?

Also, could you consider updating https://github.com/containerd/accelerated-container-image/releases/tag/v0.5.2 to note that the hash was changed?

**Comment by AkihiroSuda** [comment]
Also please release v0.5.3 or v0.6.0 to create a "clean" entry on sum.golang.org

**Comment by liulanzheng** [comment]
@AkihiroSuda  before the releases were only used to release installation packages for users, and did not consider it for downstream. Nerdctl is the only one use this in go mod. I'm not sure the previous version of 0.5.2, is it possible to solve the checksum problem by using new version?

**Comment by liulanzheng** [comment]
sorry, what does 'create a "clean" entry on sum.golang.org' mean?

**Comment by paralin** [comment]
@liulanzheng There's now two versions for v0.5.2 in existence, the original one (which is cached on sum.golang.org) and the one you force pushed. So he's asking you to make a new release tag that has only 1 single commit hash associated with it.

**Comment by AkihiroSuda** [comment]
> is it possible to solve the checksum problem by using new version?

Tried to update `go.sum` to use the new sum but Go still refuse to use the package. So releasing v0.5.3 would be highly appreciated. 🙏
