### ISSUE TITLE
Converter: switch to oci image manifest

### ISSUE THREAD

**Issue by northtyphoon** [containerd/accelerated-container-image#170]
Currently converted overlaybd image uses [Image Manifest V 2, Schema 2](https://docs.docker.com/registry/spec/manifest-v2-2/). 
Since the image cannot be run by Docker client, can we consider switching to [OCI Image Manifest](https://github.com/opencontainers/image-spec/blob/main/manifest.md)?

**Comment by BigVan** [comment]
Seems reasonable. @liulanzheng @fuweid

**Comment by liulanzheng** [comment]
we can add an option for oci manifest

**Comment by liulanzheng** [comment]
#171   oci option is added to userspace convertor.

**Comment by northtyphoon** [comment]
Thanks for the update.
