### ISSUE TITLE
Support Overlaybd image pre-warm with ctr pull

### ISSUE THREAD

**Issue by shuaichang** [containerd/accelerated-container-image#173]
Current Overlaybd images are lazily loaded. In case we need to do some background image pre-warming or caching, it's a little tricky because we need to start a dummy container with the accelerated image and may be read all files or set the downloadDelay to a small number and let the background download to pull the full content.

Is it possible to support a mode that overlaybd image can be prewarmed with `ctr pull`? It is also perfectly good if it's not ctr but some other tools.

Thanks!

**Comment by yuchen0cc** [comment]
#174
