### ISSUE TITLE
How to config to skip https verify?

### ISSUE THREAD

**Issue by Bubbleioa** [containerd/accelerated-container-image#177]
I'm using private self signed registry to do tests, when I try to run container, it prints:
```
FATA[0003] failed to attach and mount for snapshot 141: failed to enable target for /sys/kernel/config/target/core/user_999999999/dev_141, failed:failed to open remote file https://10.31.144.9/v2/redis/blobs/sha256:17f939605cddb2d59a95acc98d2b81a19ba4230c7999dfdcd60564ab8d133b0d: No such file or directory: unknown
```

And the log on registry are:
```
2023-03-23 18:29:09 2023/03/23 10:29:09 http: TLS handshake error from 172.17.0.1:37112: local error: tls: bad record MAC
```

I met the problem before and fixed it by using this [config](https://github.com/containerd/containerd/blob/main/docs/hosts.md#bypass-tls-verification-example) to skip verify. I want to know how to skip https verify using dadi?

**Comment by Bubbleioa** [comment]
Add domain.crt and run update-ca-certificates solved my problem.

**Comment by BigVan** [comment]
Sorry, we will use 'https' protocol by default. 
You can manually try to modify the URL prefix here:
https://github.com/containerd/accelerated-container-image/blob/59070a76eb4b6c72aa975ef879351dec8ee43079/pkg/snapshot/storage.go#L637
