### ISSUE TITLE
Side loading compressed layer files into the cacheDir

### ISSUE THREAD

**Issue by simha-db** [containerd/accelerated-container-image#204]
### What would you like to be added?

Us side loading compressed layer files into the cacheDir supported?

I am looking into fetching the layer files out of band and saving them in the cacheDir as sha256:. Does overlaybd pickup the new files added externally to the directory after it has started? Or does it hydrate once and maintains the inventory internally until a restart? 

### Why is this needed for Accelerated Container Image?

NA

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by yuchen0cc** [comment]
discussed in https://github.com/containerd/overlaybd/issues/220
