### ISSUE TITLE
Overlaybd log output to stdout or journalctl logs

### ISSUE THREAD

**Issue by shuaichang** [containerd/accelerated-container-image#216]
### What is the version of your Accelerated Container Image

Overlaybd 0.6.12

### What would you like to be added?

In some cases it is desirable to output overlaybd logs into stdout and get logs managed by journalctl so it's a consistent operational experience. Is this something overlaybd could support?

### Why is this needed for Accelerated Container Image?

For operational consistency.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by shuaichang** [comment]
Verified that commenting this line out will redirect logs to stdout. Is it possible to make this as a config for log destination (e.g. file|stdout)

<img width="735" alt="image" src="https://github.com/containerd/accelerated-container-image/assets/28563006/e5e170b4-f4b4-4d1f-b749-bd721c74e2b3">

**Comment by lihuiba** [comment]
```
/src/src/image_service.cpp:215lread_global_config_and
set: log output file failed, errno:6
```
It's better to use LOG_ERRNO_RETURN instead of LOG_ERROR_RETURN, so that error string will be logged as well.

**Comment by lihuiba** [comment]
@shuaichang And this issue is more fit for overlaybd.

**Comment by shuaichang** [comment]
Thanks, I think we are unblocked with the suggestion to use the global "logPath":"" as a workaround, we can close this issue now.
