### ISSUE TITLE
Renaming 'FastOCI' to 'Overlaybd - Turbo OCIv1' to make its relationship with 'overlaybd' clearer

### ISSUE THREAD

**Issue by BigVan** [containerd/accelerated-container-image#218]
FastOCI image is a lightweight version of Overlaybd which only contains tgz & filesystem index. 
We should rename FastOCI as Overlaybd-TurboOCIv1 to make this format clearer.

In addition, the complete Overlaybd image will be named 'Overlaybd - Native' which is shortened to Overlaybd

"annotations": {
  "containerd.io/snapshot/overlaybd/version": "0.1.0" // for normal overlaybd-image
  "containerd.io/snapshot/overlaybd/version": "0.1.0-turbo.ociv1" //
}

**Comment by lihuiba** [comment]
and rename exising overlaybd as 'Overlaybd - Native'.
