### ISSUE TITLE
Modify Dev's Info

### ISSUE THREAD

**Issue by qi0523** [containerd/accelerated-container-image#235]
Firstly, i add a flag `policy` to nerdctl run command. In this way, overlaybd-snapshotter can get this flag's value.
Then, overlaybd-snapshotter passes the value to overlaybd. 
`err = os.WriteFile(path.Join(targetPath, "control"), ([]byte)(fmt.Sprintf("dev_config=overlaybd/%s/%s", policy, o.overlaybdConfPath(snID))), 0666)`
`
if  err != nil {
			return errors.Wrapf(err, "failed to write target dev_config for %s", targetPath)
		}
`

![20231025205237](https://github.com/containerd/accelerated-container-image/assets/42767692/7bdaed88-023a-47ca-b87e-7234bd973b9c)

Finally, overlaybd can get the value from dev's info. However, when nerdctl create a container,  it occurs `exec /bin/bash: no such file or directory`.  Does modifying the dev's info affect rootfs?

Besides，in the top snapshot of image, we can find the bash file.
![20231026071037](https://github.com/containerd/accelerated-container-image/assets/42767692/0f97e1f3-9ca0-43a2-bc57-89a3e156fa05)

The overlaybd-tcmu logs are as follow.
![20231026072137](https://github.com/containerd/accelerated-container-image/assets/42767692/5218cda7-7528-4821-bf49-27248be91629)

/proc/pid/root/bin are as follows.
![image](https://github.com/containerd/accelerated-container-image/assets/42767692/6305b7f5-da9e-4440-bebc-6125d42b86fe)

When in /proc/pid/root/ exec bash get the same as error.
![image](https://github.com/containerd/accelerated-container-image/assets/42767692/c7d581fc-9352-40f0-b263-fefb374c6444)

**Comment by qi0523** [comment]
When keeping download's config unable，get the `bin/bash: No such file or directory`. When keeping download enable, it is exit(0). Is the problem due to lazy pulling？

The image’ config cmd is `bin/bash -c cd pythonAction && python runningforever.py`, so it shouldn't be exited 0.  I cat the `runningforever.py`, it is empty.  Is Exit(0) also due to lazy pulling?

**Comment by qi0523** [comment]
The problem is because the image is not complete. I don't know why because no errors occurred when using command `/opt/overlaybd/snapshotter/ctr obdconv` .

**Comment by liulanzheng** [comment]
@qi0523  which kernel did you use？ We met some kernel that data was not synced when umount device。

**Comment by qi0523** [comment]
@liulanzheng the kernel is 5.15.0-1047-aws. Container start from other image i reconvert，it is common in kernel 5.15.0-1047-aws.

**Comment by liulanzheng** [comment]
@qi0523 I suggest to try to replace the kernel with other version.W e had a user on Azure who encountered this issue before, and resolved by updating to a new minor version.
Also you may try the userspace convertor.
