### ISSUE TITLE
Was v1.1.4 retracted?

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/accelerated-container-image#282]
I saw a dependabot PR to bump up a-c-i to v1.14:
- https://github.com/containerd/nerdctl/pull/2943

But the tag does not seem to exist: https://github.com/containerd/accelerated-container-image/tags

**Comment by BigVan** [comment]
Yes..we change the v1.1.4 to an RC version...
Can the dependabot use the v1.1.3? Or we can create the tag v1.1.4 if you need it.
