### ISSUE TITLE
Unable to use rpull from container registry

### ISSUE THREAD

**Issue by mc256** [containerd/accelerated-container-image#43]
I follow the instructions on https://github.com/alibaba/accelerated-container-image/blob/main/docs/EXAMPLES.md

However, I got this error:
```
➜  accelerated-container-image git:(main) sudo bin/ctr rpull staging-registry.yuri.moe/redis:6.2.1_obd && sudo ctr run --net-host --snapshotter=overlaybd --rm -t staging-registry.yuri.moe/redis:6.2.1_obd demo
staging-registry.yuri.moe/redis:6.2.1_obd:                                        resolved       |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:23d8acc1c468e678019c12784bac514b09908c0accc7bf2a56ae8fe7fea9e1d6: downloading    |--------------------------------------|    0.0 B/3.3 KiB 
elapsed: 0.2 s                                                                    total:   0.0 B (0.0 B/s)                                         
done
ctr: failed to attach and mount for snapshot 7: failed to enable target for /sys/kernel/config/target/core/user_999999999/dev_7, failed:failed to open remote file https://staging-registry.yuri.moe/v2/redis/blobs/sha256:5b8ddc4be300c03f643ace1d74a62a3614224569b7d2ef46d69f4a3e96fcb856: unknown

```

------

These are the commands that run to get the OBD image and upload to my own registry.
```shell
sudo ctr content fetch registry.hub.docker.com/library/redis:6.2.1
sudo bin/ctr obdconv registry.hub.docker.com/library/redis:6.2.1 localhost:5000/redis:6.2.1_obd
sudo ctr i push  staging-registry.yuri.moe/redis:6.2.1_obd
```

I am able to lazy pull the image and run using this image `registry.hub.docker.com/overlaybd/redis:6.2.1_obd`

The registry is running and open to the public in case you would like to test that out. It is the latest image from `https://hub.docker.com/_/registry` if you want to set up your own regsitry.

**Comment by mc256** [comment]
Because of the problem above, I don't know how to generate the block-trace optimized image.

**Comment by liulanzheng** [comment]
@mc256  This is caused by the different behaviors of registries. I fix it in overlaybd (https://github.com/alibaba/overlaybd/pull/56) and you can merge it.  But I am not sure whether it completely solved and hope you to provide the version of you registry so that we can try other situations.

**Comment by mc256** [comment]
The version of my registry is `2.7.1`
https://hub.docker.com/layers/registry/library/registry/2.7.1/images/sha256-42043edfae481178f07aa077fa872fcc242e276d302f4ac2026d9d2eb65b955f?context=explore

**Comment by mc256** [comment]
Thanks! It seems to work now. But it does not work for a second attempt, I will have to reboot the computer.
```
sudo bin/ctr rpull staging-registry.yuri.moe/redis:6.2.1_obd && sudo ctr run --net-host --snapshotter=overlaybd --rm -t staging-registry.yuri.moe/redis:6.2.1_obd demo
staging-registry.yuri.moe/redis:6.2.1_obd: resolving      |--------------------------------------| 
elapsed: 0.1 s                             total:   0.0 B (0.0 B/s)                                         
done
ctr: failed to attach and mount for snapshot 7: failed to write target max_data_area_mb for /sys/kernel/config/target/core/user_999999999/dev_7: write /sys/kernel/config/target/core/user_999999999/dev_7/control: invalid argument: unknown
```

Do you have any idea why it gives this error?

**Comment by mc256** [comment]
It is weird, I can no longer run the container, it gives me this error:
```
ctr: failed to attach and mount for snapshot 7: failed to mount /dev/sdd to /var/lib/overlaybd/snapshots/7/block/mountpoint: read-only file system: unknown
```

**Comment by liulanzheng** [comment]
@mc256  so sorry for toooooo loooooong time - -!
In these days i tried registry v2.7.1 and it worked. your error about "failed to write target max_data_area_mb" is about failing to set a tcmu parameter. So i think the problem is related to tcmu kernel modules, you may try a newer kernel?  
If new kernel worked, i will make it ignore this error for compatibility.
