### ISSUE TITLE
container start error when host reboot

### ISSUE THREAD

**Issue by wxx213** [containerd/accelerated-container-image#87]
Reproduce:

1. create container
`ctr -n k8s.io run --runtime io.containerd.runc.v2 -t -d --snapshotter=overlaybd $dadi_image test_dadi bash`
2. after reboot the host, start the container
`ctr -n k8s.io t start -d test_dadi`
3. then the error occur 
`ctr: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "bash": executable file not found in $PATH: unknown`

This is because the block device is not created and mount after host reboot.

As I can see in the codes, the function attachAndMountBlockDevice  that create and mount the block device is only  called in Prepare and View interface.  But for container start, only Mount interface is called so the block device cannot be created and mount.

I think the function attachAndMountBlockDevice should also be called in Mount interface to create and mount the block device?

**Comment by BigVan** [comment]
Yep. 
It seems 'attachAndMountBlockDevice' should be called before Mount to ensure the device has been created
