### ISSUE TITLE
can not lazy pull 

### ISSUE THREAD

**Issue by fannaihao** [containerd/accelerated-container-image#96]
I can only pull the whole image, then run;
/var/log/overlaybd.log prints:
`2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|main.cpp:301|dev_open:create image file failed
2022/01/26 20:21:11|INFO |th=0000000002AA8F60|main.cpp:291|dev_open:dev open /var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/116/block/config.v1.json
2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|config_util.h:53|ParseJSON:error open json file: /var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/116/block/config.v1.json
2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|image_service.cpp:273|create_image_file:error parse image config
2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|main.cpp:301|dev_open:create image file failed
2022/01/26 20:21:11|INFO |th=0000000002AA8F60|main.cpp:291|dev_open:dev open /var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/117/block/config.v1.json
2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|config_util.h:53|ParseJSON:error open json file: /var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/117/block/config.v1.json
2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|image_service.cpp:273|create_image_file:error parse image config
2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|main.cpp:301|dev_open:create image file failed
2022/01/26 20:21:11|INFO |th=0000000002AA8F60|main.cpp:291|dev_open:dev open /var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/118/block/config.v1.json
2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|config_util.h:53|ParseJSON:error open json file: /var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/118/block/config.v1.json
2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|image_service.cpp:273|create_image_file:error parse image config
2022/01/26 20:21:11|ERROR|th=0000000002AA8F60|main.cpp:301|dev_open:create image file failed
2022/01/26 20:23:07|INFO |th=00007F25202143C0|main.cpp:291|dev_open:dev open /var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/22/block/config.v1.json
2022/01/26 20:23:07|INFO |th=00007F24DEA0D840|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 50092870, idx_bytes: 94604, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DE206C00|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 8396, idx_bytes: 92, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DD1FEC80|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 14234, idx_bytes: 164, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DC9F7BC0|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 29786352, idx_bytes: 50648, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DC1F67C0|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 18883, idx_bytes: 176, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DB9F4080|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 17718, idx_bytes: 180, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DB1EC780|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 11272123, idx_bytes: 11888, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DA1E5040|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 23701322, idx_bytes: 62140, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D81D2400|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 28651120, idx_bytes: 55368, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D71C8840|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 10817, idx_bytes: 104, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D69C1800|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 10993, idx_bytes: 100, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D61BDBC0|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 68894, idx_bytes: 448, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D59BCC40|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 28635014, idx_bytes: 62144, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D51B7C80|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 13938, idx_bytes: 104, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D49AF3C0|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 11050, idx_bytes: 92, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DF211400|zfile.cpp:509|load_jump_table:trailer_offset: 4737183, idx_offset: 4207947, idx_bytes: 529236, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DDA03800|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 150863644, idx_bytes: 284256, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D79CE840|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 19540623, idx_bytes: 45988, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24DA9EB040|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 9392, idx_bytes: 92, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D99DEC80|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 13495, idx_bytes: 104, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D91D6FC0|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 10207, idx_bytes: 100, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F24D89D4BC0|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 10073, idx_bytes: 92, dict_size: 0, use_dict: 0
2022/01/26 20:23:07|INFO |th=00007F25202143C0|image_file.cpp:262|open_lowers:LSMT::open_files_ro(files, 22) success
2022/01/26 20:23:07|INFO |th=00007F25202143C0|image_file.cpp:362|init_image_file:RW layer path not set. return RO layers.
2022/01/26 20:23:07|INFO |th=00007F25202143C0|image_file.cpp:148|start_bk_dl_thread:no need to download
2022/01/26 20:23:07|INFO |th=00007F25202143C0|image_file.h:50|ImageFile:new imageFile, bs: 512, size: 68719476736`

I can't find dir `/var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/x` find in log on the host.
I can't tell which componet get in trouble.
Any help will be aappreciated.

**Comment by fannaihao** [comment]
when I convert image, somthing wrong happens:
`Jan 26 22:50:07 bddwd-ebs-testsop-0014 kernel: se_dev->se_dev_ptr already set for storage object
Jan 26 22:50:07 bddwd-ebs-testsop-0014 overlaybd-snapshotter: time="2022-01-26T22:50:07+08:00" level=warning msg="failed to clean target dir /sys/kernel/config/target/core/user_999999999/dev_114" error="unlinkat /sys/kernel/config/target/core/user_999999999/dev_114/statistics/scsi_lu/creation_time: operation not permitted"
Jan 26 22:50:07 bddwd-ebs-testsop-0014 overlaybd-snapshotter: time="2022-01-26T22:50:07+08:00" level=error msg="failed to enable target for /sys/kernel/config/target/core/user_999999999/dev_114, "
Jan 26 22:50:07 bddwd-ebs-testsop-0014 overlaybd-snapshotter: time="2022-01-26T22:50:07+08:00" level=debug msg="Walk (fs: [])"
Jan 26 22:50:07 bddwd-ebs-testsop-0014 overlaybd-snapshotter: time="2022-01-26T22:50:07+08:00" level=debug msg="Remove (key: default/236/overlaybd-conv-sha256:a8b5fca80efae55088290f3da8110d7742de55c2a378d5ab53226a483f390e21)"
`Jan 26 22:50:40 bddwd-ebs-testsop-0014 overlaybd-snapshotter: time="2022-01-26T22:50:40+08:00" level=info msg="snapshot R/W label: 0"
Jan 26 22:50:40 bddwd-ebs-testsop-0014 overlaybd-snapshotter: time="2022-01-26T22:50:40+08:00" level=debug msg="return mount point(R/W mode: 0): [{bind /var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/114/fs [rw rbind]}]"
Jan 26 22:50:41 bddwd-ebs-testsop-0014 overlaybd-snapshotter: time="2022-01-26T22:50:41+08:00" level=debug msg="Commit (key: default/238/overlaybd-conv-907950493-64VQ, name: default/239/overlaybd-conv-sha256:a8b5fca80efae55088290f3da8110d7742de55c2a378d5ab53226a483f390e21)"
Jan 26 22:50:41 bddwd-ebs-testsop-0014 overlaybd-snapshotter: time="2022-01-26T22:50:41+08:00" level=debug msg="Commit info (id: 114, info: map[], stype: 2)"
Jan 26 22:50:41 bddwd-ebs-testsop-0014 overlaybd-snapshotter: time="2022-01-26T22:50:41+08:00" level=debug msg="Commit info (info: map[containerd.io/snapshot/overlaybd.localcommitpath:/var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/snapshots/114/fs/overlaybd.commit])"`

**Comment by BigVan** [comment]
Did you pull the latest code?  
    Restart the snapshotter service or try to clean all code and run `INSTALL.sh`. The snapshotter workdir will automatically set like "/var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/"

**Comment by fannaihao** [comment]
> Did you pull the latest code? Restart the snapshotter service or try to clean all code and run `INSTALL.sh`. The snapshotter's workdir will be automatically set like "/var/lib/containerd/io.containerd.snapshotter.v1.overlaybd/"

do as you say, but there is a new problem:

`# bin/ctr run --net-host --snapshotter=overlaybd --rm -t iregistry.baidu-int.com/dadi_research/disp-dadi2:latest demo`
`ctr: failed to attach and mount for snapshot 285: failed to enable target for /sys/kernel/config/target/core/user_999999999/dev_285, failed:failed to open switch file `https://iregistry.baidu-int.com/v2/dadi_research/disp-dadi2/blobs/sha256:4be81e0b58739a9db1d7caeffb920751ecd6f86b91f77ef42a6450315f31c98d: unknown`

/var/log/overlaybd.log:
`2022/02/11 19:57:04|INFO |th=00007FCA7DF14C40|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 8038, idx_bytes: 92, dict_size: 0, use_dict: 0
2022/02/11 19:57:04|INFO |th=00007FCA731EE000|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 1120, idx_bytes: 16, dict_size: 0, use_dict: 0
2022/02/11 19:57:04|INFO |th=00007FCA786D7F80|zfile.cpp:516|load_jump_table:read overwrite header. idx_offset: 729557225, idx_bytes: 1256316, dict_size: 0, use_dict: 0
2022/02/11 19:57:04|ERROR|th=00007FCA69FE7000|zfile.cpp:471|load_jump_table:failed to read file header. errno=125(Operation canceled)
2022/02/11 19:57:04|ERROR|th=00007FCA69FE7000|zfile.cpp:540|zfile_open_ro:failed load_jump_table, fallocate result: 0
2022/02/11 19:57:04|ERROR|th=00007FCA69FE7000|zfile.cpp:471|load_jump_table:failed to read file header. errno=125(Operation canceled)
2022/02/11 19:57:04|ERROR|th=00007FCA69FE7000|zfile.cpp:540|zfile_open_ro:failed load_jump_table, fallocate result: 0
2022/02/11 19:57:04|ERROR|th=00007FCA69FE7000|zfile.cpp:471|load_jump_table:failed to read file header. errno=125(Operation canceled)
2022/02/11 19:57:04|ERROR|th=00007FCA69FE7000|zfile.cpp:548|zfile_open_ro:failed to read index for file: 0000000003CE7D40 errno=125(Operation canceled)
2022/02/11 19:57:04|ERROR|th=00007FCA69FE7000|switch_file.cpp:189|new_switch_file:zfile_open_ro failed, path: : error: 5(Input/output error)
2022/02/11 19:57:04|ERROR|th=00007FCA69FE7000|image_file.cpp:114|__open_ro_remote:failed to open switch file https://iregistry.baidu-int.com/v2/dadi_research/disp-dadi2/blobs/sha256:4be81e0b58739a9db1d7caeffb920751ecd6f86b91f77ef42a6450315f31c98d
2022/02/11 19:57:04|ERROR|th=00007FCA69FE7000|image_file.cpp:195|do_parallel_open_files:failed to open files
2022/02/11 19:57:04|ERROR|th=00007FCA7F7243C0|image_file.cpp:250|open_lowers:layer index 56 open failed, exit.
2022/02/11 19:57:06|ERROR|th=00007FCA7F7243C0|image_file.cpp:357|init_image_file:open lower layer failed.
2022/02/11 19:57:06|ERROR|th=00007FCA7F7243C0|main.cpp:301|dev_open:create image file failed`

It says zfile run into an io error;

**Comment by liulanzheng** [comment]
https://github.com/containerd/overlaybd/pull/82

**Comment by liulanzheng** [comment]
@fannaihao  Please try whether it has been fixed  :-)
