### ISSUE TITLE
why "index=off" is added to the overlayfs mount option by default

### ISSUE THREAD

**Issue by wxx213** [containerd/accelerated-container-image#99]
From the [code](https://github.com/containerd/accelerated-container-image/blob/main/pkg/snapshot/overlay.go#L222) I can see "index=off" is added to the overlay mount option by default.

But according [kernel overlayfs document](https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html#non-standard-behavior) , enable “inode index” feature will make overlayfs act more like a standards compliant filesystem which will reduce customer's confusion when use overlayfs.

Is there any other consideration for this? I haven't see some security problem or performance regression report when enable these [features](https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html#non-standard-behavior).

**Comment by liulanzheng** [comment]
Our snapshotter is based on [containerd overlay snapshotter](https://github.com/containerd/containerd/blob/main/snapshots/overlay/overlay.go), and this part of code is the same as containerd.
I found the [related commit](https://github.com/containerd/containerd/commit/d36810d66d87f08b09003b2e2455bcabe116ab08) in containerd, that used index=off to fix EBUSY on mount.

**Comment by wxx213** [comment]
> Our snapshotter is based on [containerd overlay snapshotter](https://github.com/containerd/containerd/blob/main/snapshots/overlay/overlay.go), and this part of code is the same as containerd. I found the [related commit](https://github.com/containerd/containerd/commit/d36810d66d87f08b09003b2e2455bcabe116ab08) in containerd, that used index=off to fix EBUSY on mount.

Okay, I got it, thanks
